// src/lib/mockTasks.ts
import { Task } from "./types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Complete project documentation",
    description: "Write up all project details and specifications",
    due_date: new Date(Date.now() + 86400000).toISOString(),
    photo_url: null,
    url_link: "https://example.com/docs",
    owner_id: "user-1",
    parent_task_id: null,
    parent_task: null,
    pinned: true,
    status: "pending",
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Client meeting",
    description: "Discuss project timeline and deliverables",
    due_date: new Date(Date.now() - 86400000).toISOString(),
    photo_url: null,
    url_link: null,
    owner_id: "user-2",
    parent_task_id: null,
    parent_task: null,
    pinned: false,
    status: "overdue",
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Review code changes",
    description: null,
    due_date: new Date(Date.now() + 172800000).toISOString(),
    photo_url: null,
    url_link: null,
    owner_id: "user-3",
    parent_task_id: null,
    parent_task: null,
    pinned: false,
    status: "pending",
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];