// src/lib/mockDataTasks.ts
import { Task } from '@/types';

export const mockDataTasks: Task[] = [
  {
    id: '1',
    title: 'Project documentation',
    description: 'Write up all project details and specifications',
    due_date: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
    photo_url: null,
    url_link: 'https://example.com/docs',
    owner_id: 'user-1',
    parent_task_id: null,
    parent_task: null,
    pinned: true,
    status: 'pending',
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Client meeting',
    description: 'Discuss project timeline and deliverables',
    due_date: new Date(Date.now() - 86400000).toISOString(), // Yesterday
    photo_url: null,
    url_link: null,
    owner_id: 'user-2',
    parent_task_id: null,
    parent_task: null,
    pinned: false,
    status: 'overdue',
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Review code changes',
    description: null,
    due_date: new Date(Date.now() + 172800000).toISOString(), // 2 days
    photo_url: null,
    url_link: null,
    owner_id: 'user-3',
    parent_task_id: null,
    parent_task: null,
    pinned: false,
    status: 'pending',
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Follow up on docs',
    description: 'Address reviewer comments on project docs',
    due_date: new Date(Date.now() + 43200000).toISOString(), // 12 hours
    photo_url: null,
    url_link: 'https://example.com/docs/feedback',
    owner_id: 'user-2',
    parent_task_id: '1',
    parent_task: {
      id: '1',
      title: 'Project documentation',
      description: 'Write up all project details and specifications',
      photo_url: null,
      url_link: 'https://example.com/docs',
    },
    pinned: false,
    status: 'pending',
    assignee_id: 'user-3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Update timeline',
    description: 'Revise schedule based on client feedback',
    due_date: null, // Test nullable due_date
    photo_url: null,
    url_link: null,
    owner_id: 'user-1',
    parent_task_id: null,
    parent_task: null,
    pinned: false,
    status: 'pending',
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Design mockups',
    description: 'Complete UI designs for client review',
    due_date: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    photo_url: 'https://example.com/mockup.png',
    url_link: null,
    owner_id: 'user-3',
    parent_task_id: null,
    parent_task: null,
    pinned: false,
    status: 'complete', // Test complete status
    assignee_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
