# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json and package-lock.json
    schedule:
      interval: "weekly" # Check for updates weekly
    open-pull-requests-limit: 10 # Limit to 10 open PRs
