export default {
  plugins: {
    tailwindcss: {},
    "@fullhuman/postcss-purgecss": {
      content: [
        "./src/**/*.{ts,tsx,js,jsx}",
        "./public/index.html",
        "./src/styles/**/*.{css}",
      ],
      defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
      safelist: {
        standard: [
          "html",
          "body",
          "loading-spinner",
          "timer-container",
          "timer-ring",
          "timer-progress",
          "timer-text",
          "loading-unified-spinner",
          "shadow-unified-sm",
          "shadow-unified-md",
          "shadow-unified-lg",
          "shadow-unified-focus",
          "will-change-unified",
          "gpu-accelerated-unified",
          "optimize-rendering-unified",
          "grid-unified-responsive",
          "fixed",
          "bottom-6",
          "right-6",
          "bottom-4",
          "right-4",
          "rounded-full",
          "bg-primary",
          "text-primary-foreground",
          "shadow-lg",
          "hover:bg-primary/90",
          "focus:ring-2",
          "focus:ring-primary",
          "focus:ring-offset-2",
          "hover:scale-105",
          "active:scale-95",
          "h-14",
          "w-14",
          "h-12",
          "w-12",
          "z-[9999]",
        ],
        greedy: [/^task-/, /^status-/, /data-status/, /^virtualized-task-/],
      },
    },
    autoprefixer: {},
  },
};
