
// tailwind.config.ts
import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  safelist: [
    'text-destructive',
    'text-success',
    'text-primary',
    'text-gray-600',
    'text-gray-900',
    'text-gray-500',
    'text-gray-100',
    'text-foreground',
    'text-white',
    'text-blue-600',
    'text-blue-400',
    'text-red-600',
    'text-red-500',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-600',
    'bg-gray-700',
    'bg-gray-800',
    'bg-white',
    'bg-primary',
    'bg-card',
    'bg-popover',
    'bg-background',
    'bg-blue-500',
    'bg-blue-600',
    'bg-blue-700',
    'bg-red-500',
    'bg-red-600',
    'bg-red-700',
    'border-gray-200',
    'border-gray-300',
    'border-gray-600',
    'border-secondary',
    'border',
    'border-primary',
    'hover:border-secondary',
    'hover:underline',
    'hover:bg-gray-50',
    'hover:bg-gray-200',
    'hover:bg-gray-600',
    'hover:bg-gray-700',
    'hover:bg-blue-600',
    'hover:bg-blue-700',
    'hover:bg-red-600',
    'hover:bg-red-700',
    'hover:text-gray-900',
    'hover:text-gray-100',
    'bg-destructive', 
    'bg-success',
    'fill-destructive',
    'fill-success',
    'fill-primary',
    'fill-white',
    'fill-gray-500',
    'fill-gray-900',
    'stroke-destructive',
    'stroke-success',
    'stroke-primary',
    'stroke-white',
    'stroke-gray-500',
    'stroke-gray-900',
    'rounded-full',
    'rounded-xl',
    'rounded-lg',
    'rounded-md',
    'rounded-sm',
    // Dark mode classes
    'dark:bg-gray-600',
    'dark:bg-gray-700',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-blue-500',
    'dark:bg-blue-600',
    'dark:bg-red-500',
    'dark:bg-red-600',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-blue-400',
    'dark:border-gray-700',
    'dark:border-gray-600',
    'dark:hover:bg-gray-600',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-blue-600',
    'dark:hover:bg-red-600',
    'dark:hover:text-gray-100',
    // Brand gradient classes
    'bg-gradient-to-r',
    'from-blue-500',
    'to-blue-600',
    'hover:from-blue-600',
    'hover:to-blue-700',
    'dark:from-blue-400',
    'dark:to-blue-500',
    'dark:hover:from-blue-500',
    'dark:hover:to-blue-600',
  ],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        sm: "640px",
        md: "768px",
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          blue: "hsl(var(--accent-blue))",
          green: "hsl(var(--accent-green))",
          yellow: "hsl(var(--accent-yellow))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        brand: {
          DEFAULT: "hsl(var(--primary))",
          light: "hsl(var(--brand-light))",
        },
        surface: {
          DEFAULT: "hsl(var(--surface))",
          foreground: "hsl(var(--surface-foreground))",
        },
        // Task status colors using CSS variables
        "task-pending": "hsl(var(--status-pending))",
        "task-overdue": "hsl(var(--status-overdue))",
        "task-complete": "hsl(var(--status-complete))",
        "task-timer": "hsl(var(--status-pending))",
        // Direct blue colors for brand buttons
        blue: {
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(10px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "var(--pulse-opacity, 0.8)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        "pulse-subtle": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite --pulse-opacity=0.8",
      },
    },
  },
  plugins: [animate],
} satisfies Config;
