/**
 * Utility Types Barrel File
 * 
 * Centralized exports for all utility types including form, validation,
 * and TypeScript helper types.
 */

// Form utility types
export type {
  FormState,
  UseFormStateOptions,
  FieldState,
  FieldProps,
  ValidationRule,
  ValidationSchema,
  ValidationResult,
  FormConfig,
  FormHelpers,
  FormSubmissionState,
  FormSubmissionResult,
  FieldArrayHelpers,
  FieldArrayProps,
  FormStep,
  MultiStepFormState,
  MultiStepFormHelpers,
  ConditionalField,
  DynamicFormConfig,
  FormPersistenceConfig,
  AutoSaveConfig,
  AutoSaveState,
  FormAccessibilityConfig,
  FormOptimizationConfig,
  FormAnalytics,
  FormError,
  FormErrorBoundaryState,
  FormContextValue,
} from './form.types';

// Validation utility types
export type {
  ValidationResult as UtilityValidationResult,
  ValidationDetail,
  ValidationOptions,
  ValidationRule as UtilityValidationRule,
  AsyncValidationRule,
  ConditionalValidationRule,
  RequiredRule,
  LengthRule,
  PatternRule,
  RangeRule,
  EmailRule,
  UrlRule,
  DateRule,
  CustomRule,
  FieldValidationRule,
  ValidationSchema as UtilityValidationSchema,
  SchemaValidationOptions,
  ValidationContext,
  FieldValidationState,
  ValidationStrategy,
  ValidationConfig,
  CrossFieldValidation,
  DependentValidation,
  ConditionalValidation,
  AggregatedValidationResult,
  ValidationMetrics,
  ValidationCache,
  ValidationMessages,
  ValidationLocale,
  ValidationTransformer,
  ValidationPipeline,
  ValidationError,
  ValidationErrorHandler,
  ValidationUtilities,
  ValidationMiddleware,
} from './validation.types';

// TypeScript helper types
export type {
  DeepPartial,
  DeepRequired,
  DeepReadonly,
  Mutable,
  StringKeys,
  NumberKeys,
  SymbolKeys,
  KeysOfType,
  OptionalKeys,
  RequiredKeys,
  Merge,
  Override,
  PartialExcept,
  RequiredExcept,
  OmitByType,
  PickByType,
  ArgumentTypes,
  ReturnTypeAsync,
  FirstArgument,
  LastArgument,
  Head,
  Tail,
  Last,
  Length,
  Reverse,
  Flatten,
  Split,
  Join,
  Capitalize,
  Uncapitalize,
  CamelCase,
  SnakeCase,
  If,
  IsAny,
  IsNever,
  IsUnknown,
  IsEqual,
  IsArray,
  IsFunction,
  IsObject,
  Brand,
  Branded,
  Unbrand,
  EventMap,
  EventHandler,
  EventHandlers,
  Awaited,
  PromiseType,
  MaybePromise,
  PromiseValue,
  JsonPrimitive,
  JsonValue,
  JsonObject,
  JsonArray,
  Jsonifiable,
  Path,
  PathValue,
  SetPath,
  TableInsert,
  TableUpdate,
  ApiResponse as HelperApiResponse,
  QueryParams,
  ValidationErrors,
  FormErrors,
  PropsWithClassName,
  PropsWithChildren,
  ComponentProps,
  ElementProps,
  StateSelector,
  StateAction,
  StateReducer,
  NonNullable,
  NonEmptyArray,
  AtLeastOne,
  OneOf,
  AllOf,
} from './helpers.types'; 