// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvdpcpsmcehzliyuqeuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZHBjcHNtY2VoemxpeXVxZXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzE3OTYsImV4cCI6MjA2MTg0Nzc5Nn0.CEwC7Zitceyc5QB4SpxzczJ4hdW4Ub6o0FfJKPErSpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);